export const services = {
	services_0: [
		{
			id: 0,
			nameKey: "med_est_i_reg.0.name",
			priceKey: "med_est_i_reg.0.price",
			currencyKey: "med_est_i_reg.0.currency",
			description: "med_est_i_reg.0.description",
		},
		{
			id: 1,
			nameKey: "med_est_i_reg.1.name",
			priceKey: "med_est_i_reg.1.price",
			currencyKey: "med_est_i_reg.1.currency",
			description: "med_est_i_reg.1.description",
		},
		{
			id: 2,
			nameKey: "med_est_i_reg.2.name",
			priceKey: "med_est_i_reg.2.price",
			currencyKey: "med_est_i_reg.2.currency",
			description: "med_est_i_reg.2.description",
		},
		{
			id: 3,
			nameKey: "med_est_i_reg.3.name",
			priceKey: "med_est_i_reg.3.price",
			currencyKey: "med_est_i_reg.3.currency",
			description: "med_est_i_reg.3.description",
		},
		{
			id: 4,
			nameKey: "med_est_i_reg.4.name",
			priceKey: "med_est_i_reg.4.price",
			currencyKey: "med_est_i_reg.4.currency",
			description: "med_est_i_reg.4.description",
		},
		{
			id: 5,
			nameKey: "med_est_i_reg.5.name",
			priceKey: "med_est_i_reg.5.price",
			currencyKey: "med_est_i_reg.5.currency",
			description: "med_est_i_reg.5.description",
		},
	],
	services_1: [
		{
			id: 0,
			nameKey: "dep_las_dla_kob.0.name",
			priceKey: "dep_las_dla_kob.0.price",
			currencyKey: "dep_las_dla_kob.0.currency",
			description: "dep_las_dla_kob.0.description",
		},
		{
			id: 1,
			nameKey: "dep_las_dla_kob.1.name",
			priceKey: "dep_las_dla_kob.1.price",
			currencyKey: "dep_las_dla_kob.1.currency",
			description: "dep_las_dla_kob.1.description",
		},
		{
			id: 2,
			nameKey: "dep_las_dla_kob.2.name",
			priceKey: "dep_las_dla_kob.2.price",
			currencyKey: "dep_las_dla_kob.2.currency",
			description: "dep_las_dla_kob.2.description",
		},
		{
			id: 3,
			nameKey: "dep_las_dla_kob.3.name",
			priceKey: "dep_las_dla_kob.3.price",
			currencyKey: "dep_las_dla_kob.3.currency",
			description: "dep_las_dla_kob.3.description",
		},
		{
			id: 4,
			nameKey: "dep_las_dla_kob.4.name",
			priceKey: "dep_las_dla_kob.4.price",
			currencyKey: "dep_las_dla_kob.4.currency",
			description: "dep_las_dla_kob.4.description",
		},
		{
			id: 5,
			nameKey: "dep_las_dla_kob.5.name",
			priceKey: "dep_las_dla_kob.5.price",
			currencyKey: "dep_las_dla_kob.5.currency",
			description: "dep_las_dla_kob.5.description",
		},
	],
	services_2: [
		{
			id: 0,
			nameKey: "dep_las_dla_mez.0.name",
			priceKey: "dep_las_dla_mez.0.price",
			currencyKey: "dep_las_dla_mez.0.currency",
			description: "dep_las_dla_mez.0.description",
		},
		{
			id: 1,
			nameKey: "dep_las_dla_mez.1.name",
			priceKey: "dep_las_dla_mez.1.price",
			currencyKey: "dep_las_dla_mez.1.currency",
			description: "dep_las_dla_mez.1.description",
		},
		{
			id: 2,
			nameKey: "dep_las_dla_mez.2.name",
			priceKey: "dep_las_dla_mez.2.price",
			currencyKey: "dep_las_dla_mez.2.currency",
			description: "dep_las_dla_mez.2.description",
		},
		{
			id: 3,
			nameKey: "dep_las_dla_mez.3.name",
			priceKey: "dep_las_dla_mez.3.price",
			currencyKey: "dep_las_dla_mez.3.currency",
			description: "dep_las_dla_mez.3.description",
		},
		{
			id: 4,
			nameKey: "dep_las_dla_mez.4.name",
			priceKey: "dep_las_dla_mez.4.price",
			currencyKey: "dep_las_dla_mez.4.currency",
			description: "dep_las_dla_mez.4.description",
		},
		{
			id: 5,
			nameKey: "dep_las_dla_mez.5.name",
			priceKey: "dep_las_dla_mez.5.price",
			currencyKey: "dep_las_dla_mez.5.currency",
			description: "dep_las_dla_mez.5.description",
		},
	],
};
